openapi: 3.0.0
info:
  title: Flights CRUD Application
  description: API for managing flights
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
components:
  schemas:
    Flight:
      type: object
      properties:
        flightNumber:
          type: string
        departure:
          type: string
        destination:
          type: string
        departureTime:
          type: string
          format: date-time
        arrivalTime:
          type: string
          format: date-time
        aircraft:
          type: string
        status:
          type: string
          enum:
            - scheduled
            - departed
            - arrived
            - cancelled
paths:
  /flights:
    get:
      summary: Get all flights
      responses:
        "200":
          description: A list of flights
        "500":
          description: Internal server error
    post:
      summary: Create a new flight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Flight"
      responses:
        "201":
          description: Flight created successfully
        "400":
          description: Bad request (e.g., validation error)
        "500":
          description: Internal server error
  /flights/{flightNumber}:
    get:
      summary: Get a flight by flight number
      parameters:
        - name: flightNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Flight details
        "404":
          description: Flight not found
        "500":
          description: Internal server error
    patch:
      summary: Update a flight
      parameters:
        - name: flightNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Flight"
      responses:
        "200":
          description: Flight updated successfully
        "400":
          description: Bad request (e.g., validation error)
        "404":
          description: Flight not found
        "500":
          description: Internal server error
    delete:
      summary: Cancel a flight
      parameters:
        - name: flightNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Flight cancelled successfully
        "404":
          description: Flight not found
        "500":
          description: Internal server error
