openapi: 3.0.0
info:
  title: Flights CRUD Application
  description: API for managing flights
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
